// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DelTask(arg1:string):Promise<void>;

export function GetAllTask():Promise<Array<main.TaskConf>>;

export function GetTask(arg1:string):Promise<main.TaskConf>;

export function IsTaskRun(arg1:string):Promise<boolean>;

export function Quit():Promise<void>;

export function SaveTask(arg1:main.TaskConf):Promise<void>;

export function StartTask(arg1:string,arg2:string,arg3:Array<main.Port>):Promise<void>;

export function StopTask(arg1:string):Promise<void>;
