// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DelTask(arg1) {
  return window['go']['main']['App']['DelTask'](arg1);
}

export function GetAllTask() {
  return window['go']['main']['App']['GetAllTask']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function IsTaskRun(arg1) {
  return window['go']['main']['App']['IsTaskRun'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveTask(arg1) {
  return window['go']['main']['App']['SaveTask'](arg1);
}

export function StartTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTask'](arg1, arg2, arg3);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}
